//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ITStudioEntities : DbContext
{
    public ITStudioEntities()
        : base("name=ITStudioEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<admins> admins { get; set; }
    public DbSet<applications> applications { get; set; }
    public DbSet<members> members { get; set; }
    public DbSet<notices> notices { get; set; }
    public DbSet<works> works { get; set; }
    public DbSet<workTypes> workTypes { get; set; }
    public DbSet<outWorks> outWorks { get; set; }
}
